include(
    ":notifier",
    ":device",
    ":logger:lib",
    ":logger:logcat",
    ":logger:crashlytics",
    ":tracker:lib",
    ":tracker:firebase",
    ":tracker:google-analytics",
    ":tracker:amplitude",
    ":tracker:segment",
)
