include(
    ":notifier",
    ":device",
    ":logger",
    ":logger-logcat",
    ":logger-crashlytics",
    ":tracker",
    ":tracker-firebase",
    ":tracker-google-analytics",
    ":tracker-amplitude",
    ":tracker-segment",
)
