[versions]
kotlin = "2.4.20"
ktlint = "14.2.0"
agp = "9.4.1"

# Tracker/logger extensions
firebaseCore = "21.1.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Tracker/logger extensions
tracker-firebase = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
